//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Pacjent
    {
        [Display(Name = "ID")]
        public int PacjentID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        [Display(Name = "Desease")]
        public string Choroba { get; set; }
        [Display(Name = "Date of Birth")]
        [DataType(DataType.Date)]
        public System.DateTime Date { get; set; }
        public string Telefon { get; set; }
        [Display(Name = "Doctor")]
        public int DoctorID { get; set; }
    
        public virtual Doctor Doctor { get; set; }
    }
}
